Add workflows
AlibabaRazboinik/habit_tracker pull request #120
Opened 2022-11-21 16:26 UTC by SmoothDenis

A few improvements: 
- automatic build 
- publication in the register (create your account and secrets, the repository will also need to be replaced)

2022-11-21 16:27 UTC, SmoothDenis commented
Check that the dependencies I added are correct for your local testing

2022-12-07 18:44 UTC, AlibabaRazboinik requested changes

2022-12-07 18:44 UTC, AlibabaRazboinik commented on Dockerfile
> +RUN echo $PROD_CONF > /home/app/src/main/resources/application.properties && echo $TEST_CONF > /home/app/src/test/resources/application.properties
удали эту строку

2022-12-07 18:44 UTC, AlibabaRazboinik commented on .github/workflows/to_dockerhub.yml
> +          tags: smoothdenis/habit-tracker:latest
заменить на korvalanni/habit_tracker:latest

2022-12-07 18:47 UTC, merged