Валидация значений на входе в контроллер
AlibabaRazboinik/habit_tracker pull request #68
Opened 2022-11-09 12:38 UTC by lkorasik

https://github.com/AlibabaRazboinik/habit_tracker/issues/51

2022-11-10 21:27 UTC, SonyaGB requested changes
тесты не проходят

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/validators/OnlyLettersDigitsUnderscoreValidator.java
> +            if(!((Character.isLetter(character)) || (Character.isDigit(character)) || (character == '_')))
Думаю, что человекочитаемее будет следующий вариант 
`if (!Character.isLetter(character) && !Character.isDigit(character) && character != '_')`

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/validators/AtLeastOneLetterValidator.java
> +        if (value == null)
Если `value == null`, то это означает, что тут есть хотя бы один символ ?

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/validators/OnlyLettersDigitsUnderscoreValidator.java
> +public class OnlyLettersDigitsUnderscoreValidator implements ConstraintValidator<OnlyLettersDigitsUnderscore, String> {
java-doc (везде на валидаторы и анноотации)

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/validators/AtLeastOneDigitValidator.java
> +        if (value == null)
если `value == null`, то это означает, что есть цифра ?

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/annotations/OnlyLettersDigitsUnderscore.java
> +    Class<?>[] groups() default {};
неиспользуемые поля, если их планируется использовать в дальнейшем, то в следующей задаче и добавим, другие аннотации тоже проверьте

2022-11-10 21:27 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/validation/annotations/OnlyLettersDigitsUnderscore.java
> +import com.example.habitstracker.validation.validators.AtLeastOneLetterValidator;
лишний импорт Ctrl+O

2022-11-11 10:10 UTC, lkorasik commented on src/main/java/com/example/habitstracker/validation/annotations/OnlyLettersDigitsUnderscore.java
> +    Class<?>[] groups() default {};
Их нельзя убрать. Посмотри документацию к ```@Constraint```

2022-11-11 10:23 UTC, lkorasik commented on src/test/java/com/example/habitstracker/api/AuthTest.java
> +        user = new TestUserBuilder().build();
Есть задача #78

2022-11-11 10:49 UTC, lkorasik commented on src/main/java/com/example/habitstracker/advices/UserAdvice.java
> +                .map(error -> new ErrorResponseDTO().codeError(0).message(error.getDefaultMessage()))
Задача #80

2022-11-11 13:22 UTC, lkorasik commented on src/test/java/com/example/habitstracker/TestUserBuilder.java
> +    private HabitList habitList = new HabitList("Habits");
Задача #78

2022-11-11 16:20 UTC, merged

2022-11-11 16:21 UTC, lkorasik commented
Close #51