Починить тест test_incorrectPassword
AlibabaRazboinik/habit_tracker pull request #72
Opened 2022-11-10 17:56 UTC by lkorasik

https://github.com/AlibabaRazboinik/habit_tracker/issues/55

2022-11-10 22:37 UTC, SonyaGB requested changes
Не работает clone, а в целом всё норм

2022-11-10 22:37 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/mappers/UserMapper.java
> +    public static LoginPasswordDTO toLoginPassword(User user) {
java-doc на публичный метод

2022-11-10 22:37 UTC, SonyaGB commented on src/main/java/com/example/habitstracker/models/User.java
> +public class User implements Cloneable {
clone у Object это поверхностное копирования, т.е. копия HabbitList не создается, а пробрасывается ссылка и у них будет общий HabbitList

2022-11-11 06:12 UTC, lkorasik commented on src/main/java/com/example/habitstracker/models/User.java
> +public class User implements Cloneable {
Да. Пока не возникло необходимости в реализации полного копирования, поэтому копирование реализовано вот так.

2022-11-11 16:54 UTC, merged